### ISSUE TITLE
Confirm what sensors are available for  which model of car

### ISSUE THREAD

**Issue by lonebaggie** [hacf-fr/hassRenaultZE#123]
I realise this component is developing extremely quickly, but I’m struggling to work out what sensors have been replaced or do not work for my model of Zoe (ZE40). As I update versions , I have a number of sensors which are now  unavailable
I assume location does not work for my model  , but I still have sensors for .zoe_range, zoe_millage  and  climate.zoe_HVAC  are these no longer supported?

Again many thanks for this intergration,  I use this  in conjuction with my energy tariff and it has saved me money

**Comment by epenet** [comment]
`location` doesn't work for Zoe 40
`range` was replaced with `battery autonomy`
`climate` was removed due to inconsistencies (see discussion #51, PR #114 and #116 and documentation at https://github.com/hacf-fr/hassRenaultZE/blob/master/CONFIGURE.md)

For `mileage` I don't have any problem. What is your issue with mileage? Maybe a spelling issue?

**Comment by lonebaggie** [comment]
Thanks for the update, still no mileage data 

running the renault-api 

renault-api --log status
cockpit: Access is denied for this resource
--------------------  -------------------------
Battery level         73 %
Last updated          2021-02-03 04:34:45
Range estimate        159 km
Plug state            PlugState.UNPLUGGED
Charging state        ChargeState.NOT_IN_CHARGE
Charge mode           always_charging
HVAC status           off
External temperature  6.0 °C

Is mileage data in the cockpit data ?

**Comment by epenet** [comment]
Yes mileage is part of the cockpit data. I've never heard of the cockpit data being unavailable!
What vehicle do you have?
Does the mileage show up correctly inside the Renault application?

Also, if you replace `--log` with `--debug` you should be able to see the full API responses directly in the console:
`renault-api --debug status`

**Comment by epenet** [comment]
Note 1: This should probably be discussed on renault-api rather than hassRenaultZE...
Note 2: You can take a look at this directory https://github.com/hacf-fr/renault-api/tree/main/tests/fixtures/kamereon/vehicles to check if your vehicle is in the list - if it is not then please generate a new file 
Note 3: You may with to take participate at this converstation https://github.com/hacf-fr/renault-api/pull/157

**Comment by lonebaggie** [comment]
OK many thanks for the update . will look at renault-api github . 

for info my car is
Zoe 40 Dynamique Nav R110
Renault App does not show mileage , but will allow me to manually update it 

You can close this ticket.  Its  just looks like a documentation issue,  Just was'nt sure what sensors were now supported ,Now I know :)  I can delete all the orphaned sensors from my HA.

**Comment by epenet** [comment]
We're still trying to figure out how to know if an endpoint is available, or not available. So any input on the renault-api conversations would be very welcome.
